name: Rust

on:
  push:
    branches:
      - master
      - "dev-*"
      - "feature-*"
  pull_request:
    branches:
      - master
      - "dev-*"
      - "feature-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose